# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
jobs:
  quality:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        token: ${{ secrets.PAT-SPORTS-STATIC-API }}
    - run: npm ci
    - run: npm run build
    - run: ls data
    - run: |
          git config --global user.name 'Jorge Chavez'
          git config --global user.email 'jorgecha48@gmail.com'
          git add .
          git commit -am "Automated api"
          git push